# Generated by Django 6.0.3 on 2026-03-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Темасы')),
                ('category', models.CharField(choices=[('STUDY', 'Окуган жерим'), ('VILLAGE', 'Айылым'), ('FRIENDS', 'Досторум'), ('WORK', 'Иштеген жерим'), ('GAMES', 'Оюндарым')], max_length=20, verbose_name='Бөлүм')),
                ('description', models.TextField(verbose_name='Маалымат')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Сүрөт')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
